# Generated by Django 4.1 on 2023-02-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dirigenti',
            fields=[
                ('id_dir', models.AutoField(primary_key=True, serialize=False)),
                ('nomecompleto', models.CharField(blank=True, db_column='NomeCompleto', max_length=250, null=True)),
            ],
            options={
                'db_table': 'Dirigenti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mansione',
            fields=[
                ('id_mansione', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mansione', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('data_creazione', models.DateTimeField(blank=True, null=True)),
                ('data_modifica', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, db_column='Note', null=True)),
            ],
            options={
                'db_table': 'Mansione',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsabili',
            fields=[
                ('id_res', models.AutoField(primary_key=True, serialize=False)),
                ('nomecompleto', models.CharField(blank=True, db_column='NomeCompleto', max_length=250, null=True)),
            ],
            options={
                'db_table': 'Responsabili',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsabiliSede',
            fields=[
                ('id_res_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nomecompleto', models.CharField(blank=True, db_column='NomeCompleto', max_length=250, null=True)),
            ],
            options={
                'db_table': 'Responsabili_sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sesso',
            fields=[
                ('id_sesso', models.AutoField(primary_key=True, serialize=False)),
                ('sesso', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'Sesso',
                'managed': False,
            },
        ),
    ]
