# Generated by Django 4.1 on 2023-02-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capi_area', '0002_addincforf_addrimborsi_addtrasferte_cedolini_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anadipendenti',
            options={'managed': False, 'ordering': ['cognome']},
        ),
    ]
