# Generated by Django 4.1 on 2023-02-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi_area', '0003_alter_anadipendenti_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppoggioVerificaQr',
            fields=[
                ('uuid_qr', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'appoggio_verifica_qr',
                'managed': False,
            },
        ),
    ]
