# Generated by Django 4.1 on 2023-02-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi_area', '0004_appoggioverificaqr'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentualiContratto',
            fields=[
                ('id_ore_contratto', models.AutoField(primary_key=True, serialize=False)),
                ('dicitura_percentuale', models.CharField(max_length=50)),
                ('perc_contratto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ore_contratto', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('note', models.TextField(blank=True, db_column='Note', null=True)),
            ],
            options={
                'db_table': 'Percentuali_contratto',
                'ordering': ['perc_contratto'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabellaCcnl',
            fields=[
                ('id_ccnl', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contratto', models.CharField(blank=True, max_length=250, null=True)),
                ('codice_ccnl', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tabella_ccnl',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='contratti',
            options={'managed': False, 'ordering': ['codicecontratto']},
        ),
        migrations.AlterModelOptions(
            name='tipocontratto',
            options={'managed': False, 'ordering': ['nome_contratto']},
        ),
    ]
