# Generated by Django 4.1 on 2023-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi_area', '0005_percentualicontratto_tabellaccnl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id_lista', models.BigAutoField(primary_key=True, serialize=False)),
                ('todo', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('fatta', models.IntegerField(blank=True, default=0, null=True)),
                ('gruppo', models.IntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'todo_list',
                'managed': False,
            },
        ),
    ]
