# Generated by Django 4.1 on 2023-02-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_dirigenti_mansione_responsabili_responsabilisede_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppoggioVerificaQr',
            fields=[
                ('uuid_qr', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'appoggio_verifica_qr',
                'managed': False,
            },
        ),
    ]
