# Generated by Django 4.1 on 2023-02-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_tabellaccnl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratti',
            options={'managed': False},
        ),
    ]
