# Generated by Django 4.1 on 2023-02-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_appoggioverificaqr'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabellaCcnl',
            fields=[
                ('id_ccnl', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contratto', models.CharField(blank=True, max_length=250, null=True)),
                ('codice_ccnl', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tabella_ccnl',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='contratti',
            options={'managed': False, 'ordering': ['codicecontratto']},
        ),
        migrations.AlterModelOptions(
            name='percentualicontratto',
            options={'managed': False, 'ordering': ['perc_contratto']},
        ),
        migrations.AlterModelOptions(
            name='tipocontratto',
            options={'managed': False, 'ordering': ['nome_contratto']},
        ),
    ]
